### ISSUE TITLE
Filament runout sensor 

### ISSUE THREAD

**Issue by n3roGit** [Clank50AE/Clanks-Klipper-Configs#2]
Du you have tried the filament sensor configuration? In my invention the sensor doesn't work. Maybe wrong pin?

**Comment by n3roGit** [comment]
Hello 👋? :)

**Comment by n3roGit** [comment]
i fixed it. You have to use ar2 in the config file.

**Comment by Clank50AE** [comment]
Hey there! Sorry I missed this. This is my first repo so forgive me :D
