### ISSUE TITLE
Sidewinder X1 Config (stock and bltouch) is causing "MCU 'mcu' shutdown: Not a valid input pin"

### ISSUE THREAD

**Issue by markussiebert** [Clank50AE/Clanks-Klipper-Configs#9]
Using your config worked fine for a long time, but now, i get the error MCU 'mcu' shutdown: Not a valid input pin ... no idea how to find the pin causing this problem or how to fix this...

**Comment by BlackDragonBE** [comment]
@markus7811 Try updating Klipper and re-flashing the firmware. It's possible you have the same issue as this guy: https://www.reddit.com/r/klippers/comments/p4lv2i/issue_after_update_mcu_mcu_shutdown_not_a_valid/

**Comment by markussiebert** [comment]
Thank you so much - i found this reddit, but when i saw it there was no solution ... really bad luck that I updated and flashed at the moment klipper was broken :-) so this issue can be closed...
